development:
  adapter: mysql2
  encoding: utf8
  database: react_with_rails_development
  username: react_with_rails_user
  password: react_with_rails_password
  host: localhost
  port: 3306

production:
  adapter: mysql2
  encoding: utf8
  database: react_with_rails_production
  username: react_with_rails_user
  password: react_with_rails_password
  host: localhost
  port: 3306
